Repository elementary/sideload, pull requests merged in 2019-10, with the labels that each got.

#55 Close Sideload when opening installed app
  src/Application.vala
Labels: Bitesize

#56 Only display extra remotes message if needed
  data/colors.css
  data/screenshot.png
  data/sideload.gresource.xml
  meson.build
  src/FlatpakRefFile.vala
  src/MainWindow.vala
  src/Views/MainView.vala
Labels: Needs Design

#52 Change references from 'Software' to 'App'
  data/screenshot-success.png
  data/screenshot.png
  src/Application.vala
  src/FlatpakRefFile.vala
  src/MainWindow.vala
  src/Views/ErrorView.vala
  src/Views/MainView.vala
  src/Views/SuccessView.vala
Labels: Bitesize

#71 Release 1.0.0
  data/sideload.appdata.xml.in
Labels: Release
